# Windows (https://github.com/travis-ci-tester/toolchain-table)

# Exclude broken from: https://github.com/hunter-packages/mini_chromium/blob/hunter/appveyor.yml

environment:
  matrix:
    ###
    # FIXME: see vs-14-2015
    # - TOOLCHAIN: "default"
    #   CONFIG: Release

    # - TOOLCHAIN: "default"
    #   CONFIG: Debug

    ###
    - TOOLCHAIN: "ninja-vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "ninja-vs-12-2013-win64"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "nmake-vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "nmake-vs-12-2013-win64"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "nmake-vs-12-2013"
      CONFIG: Release

    - TOOLCHAIN: "nmake-vs-12-2013"
      CONFIG: Debug

    ###
    # - TOOLCHAIN: "vs-10-2010"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-10-2010"
    #   CONFIG: Debug

    ###
    # - TOOLCHAIN: "vs-11-2012"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-11-2012"
    #   CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013-win64"
      CONFIG: Debug

    # XP doesn't work: https://ci.appveyor.com/project/ruslo/crashpad/build/1.0.1/job/jp88cvbnehtadkyy
    ###
    # - TOOLCHAIN: "vs-12-2013-xp"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-12-2013-xp"
    #   CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-12-2013"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013"
      CONFIG: Debug

    ###
    # Looks like AppVeyor's SDK 10.0.10240.0 is buggy (works fine with local 10.0.14393)
    # - TOOLCHAIN: "vs-14-2015"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-14-2015"
    #   CONFIG: Debug

    ###
    # - TOOLCHAIN: "vs-9-2008"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-9-2008"
    #   CONFIG: Debug

    ###
    # - TOOLCHAIN: "mingw"
    #   CONFIG: Release

    # - TOOLCHAIN: "mingw"
    #   CONFIG: Debug

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: 7z x master.zip
  - cmd: set POLLY_SOURCE_DIR=%cd%\polly-master

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_SOURCE_DIR%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Use MinGW from Qt tools because version is higher
  # * http://www.appveyor.com/docs/installed-software#qt
  - cmd: set MINGW_PATH=C:\Qt\Tools\mingw492_32\bin

build_script:
  # Need to have Python 2.7 in PATH
  - cmd: set PATH=C:\Python27-x64;%PATH%
  - cmd: C:\Python34-x64\python.exe %POLLY_SOURCE_DIR%\bin\build.py --toolchain "%TOOLCHAIN%" --config "%CONFIG%" --verbose --test
